import { Providers } from '@/lib/queries/queryClient';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { Suspense } from 'react';
import Loading from './loading.js';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark h-dvh`}
      >
        <main className="h-full relative">
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
